### PR TITLE
Exponential backoff for API requests

### PR DESCRIPTION
**Pull request by NickHu**
I keep getting rate-limited by the OpenAI API, and making unsuccessful requests also prevents the rate limit from resetting (https://help.openai.com/en/articles/5955604-how-can-i-solve-429-too-many-requests-errors). This PR uses the backoff crate to implement exponential backoff.

### CODE REVIEW

**Review by benwr — APPROVED** [review]
Awesome, thanks for the PR!

**Comment by benwr** [comment]
published to crates.io in 0.3.4

**Comment by NickHu** [comment]
Unfortunately, this didn't solve my problem - I didn't realise that the API call this program makes isn't free (I thought it was using ChatGPT, which *currently* is free). Maybe it would be good to have an alternative backend that isn't as expensive as OpenAI.

**Comment by benwr** [comment]
Ah, yeah, sorry about that. Very open to adding other backends! All that's required is that the backend (a) be trained on a dataset that includes a substantial number of git diffs, and (b) allow a prefix and a suffix in the prompt.

**Comment by benwr** [comment]
Maybe `codebert-base` on huggingface?

**Pull request merged**
